/* Generated by nsgenbind
 *
 * nsgenbind is published under the MIT Licence.
 * nsgenbind is similar to a compiler is a purely transformative tool which
 * explicitly makes no copyright claim on this generated output
 */

/* DukTape JavaScript bindings for NetSurf browser
 *
 * Copyright 2015 Vincent Sanders <vince@netsurf-browser.org>
 * This file is part of NetSurf, http://www.netsurf-browser.org/
 * Released under the terms of the MIT License,
 *        http://www.opensource.org/licenses/mit-license
 */

#include <dom/dom.h>

#include "utils/log.h"
#include "utils/nsurl.h"

#include "javascript/duktape/duktape.h"

struct browser_window;
struct html_content;
struct dom_node;
struct dom_element;
struct dom_document;
struct dom_html_element;
struct dom_node_character_data;
struct dom_node_text;
struct dom_node_list;
struct dom_node_comment;
struct dom_html_collection;
struct dom_html_br_element;


#include "javascript/duktape/duktape/binding.h"
#include "javascript/duktape/duktape/private.h"
#include "javascript/duktape/duktape/prototype.h"

#include "javascript/duktape/dukky.h"

static void dukky_dom_settable_token_list___init(duk_context *ctx, dom_settable_token_list_private_t *priv, struct dom_tokenlist *tokens)
{
	dukky_dom_token_list___init(ctx, &priv->parent, tokens);
#line 15 "DOMSettableTokenList.bnd"
#line 48 "dom_settable_token_list.c"
}

static void dukky_dom_settable_token_list___fini(duk_context *ctx, dom_settable_token_list_private_t *priv)
{
	dukky_dom_token_list___fini(ctx, &priv->parent);
}

static duk_ret_t dukky_dom_settable_token_list___constructor(duk_context *ctx)
{
	/* create private data and attach to instance */
	dom_settable_token_list_private_t *priv = calloc(1, sizeof(*priv));
	if (priv == NULL) return 0;
	duk_push_pointer(ctx, priv);
	duk_put_prop_string(ctx, 0, dukky_magic_string_private);

	dukky_dom_settable_token_list___init(ctx, priv, duk_get_pointer(ctx, 1));
	duk_set_top(ctx, 1);
	return 1;
}

static duk_ret_t dukky_dom_settable_token_list___destructor(duk_context *ctx)
{
	dom_settable_token_list_private_t *priv;
	duk_get_prop_string(ctx, 0, dukky_magic_string_private);
	priv = duk_get_pointer(ctx, -1);
	duk_pop(ctx);
	if (priv == NULL) return 0;

	dukky_dom_settable_token_list___fini(ctx, priv);
	free(priv);
	return 0;
}

static duk_ret_t dukky_dom_settable_token_list_value_getter(duk_context *ctx)
{
	/* Get private data for method */
	dom_settable_token_list_private_t *priv = NULL;
	duk_push_this(ctx);
	duk_get_prop_string(ctx, -1, dukky_magic_string_private);
	priv = duk_get_pointer(ctx, -1);
	duk_pop_2(ctx);
	if (priv == NULL) {
		return 0; /* can do? No can do. */
	}

#line 17 "DOMSettableTokenList.bnd"

	dom_exception exc;
	dom_string *value;

	exc = dom_tokenlist_get_value(priv->parent.tokens, &value);
	if (exc != DOM_NO_ERR) return 0; /* coerced to undefined */

	duk_push_lstring(ctx, dom_string_data(value), dom_string_length(value));
	dom_string_unref(value);

	return 1;
#line 106 "dom_settable_token_list.c"
}

static duk_ret_t dukky_dom_settable_token_list_value_setter(duk_context *ctx)
{
	/* Get private data for method */
	dom_settable_token_list_private_t *priv = NULL;
	duk_push_this(ctx);
	duk_get_prop_string(ctx, -1, dukky_magic_string_private);
	priv = duk_get_pointer(ctx, -1);
	duk_pop_2(ctx);
	if (priv == NULL) {
		return 0; /* can do? No can do. */
	}

#line 31 "DOMSettableTokenList.bnd"

	dom_exception exc;
	dom_string *value;
    duk_size_t slen;
    const char *s = duk_require_lstring(ctx, 0, &slen);

    exc = dom_string_create_interned((const uint8_t *)s, slen, &value);
    if (exc != DOM_NO_ERR) return 0;

    exc = dom_tokenlist_set_value(priv->parent.tokens, value);
    dom_string_unref(value);

    return 0;
#line 135 "dom_settable_token_list.c"
}

duk_ret_t dukky_dom_settable_token_list___proto(duk_context *ctx, void *udata)
{
	/* Set this prototype's prototype (left-parent) */
	/* get prototype */
	duk_get_global_string(ctx, dukky_magic_string_prototypes);
	duk_get_prop_string(ctx, -1, "\xFF\xFFNETSURF_DUKTAPE_PROTOTYPE_DOMTOKENLIST");
	duk_replace(ctx, -2);
	duk_set_prototype(ctx, 0);

	/* Add read/write property */
	duk_dup(ctx, 0);
	duk_push_string(ctx, "value");
	duk_push_c_function(ctx, dukky_dom_settable_token_list_value_getter, 0);
	duk_push_c_function(ctx, dukky_dom_settable_token_list_value_setter, 1);
	duk_def_prop(ctx, -4, DUK_DEFPROP_HAVE_GETTER |
		DUK_DEFPROP_HAVE_SETTER |
		DUK_DEFPROP_HAVE_ENUMERABLE | DUK_DEFPROP_ENUMERABLE |
		DUK_DEFPROP_HAVE_CONFIGURABLE);
	duk_pop(ctx);

	/* Set the destructor */
	duk_dup(ctx, 0);
	duk_push_c_function(ctx, dukky_dom_settable_token_list___destructor, 1);
	duk_set_finalizer(ctx, -2);
	duk_pop(ctx);

	/* Set the constructor */
	duk_dup(ctx, 0);
	duk_push_c_function(ctx, dukky_dom_settable_token_list___constructor, 2);
	duk_put_prop_string(ctx, -2, "\xFF\xFFNETSURF_DUKTAPE_INIT");
	duk_pop(ctx);

	return 1; /* The prototype object */
}


